### ISSUE TITLE
[Bug]: electron: The default of contextIsolation is deprecated

### ISSUE THREAD

**Issue by albertorsesc** [beyondcode/invoker-community#308]
### Operating system

Ubuntu 22.04.1

### Laravel Version

9.26.1

### PHP Version

8.0 and 8.1

### Project Location

Somewhere else (please specify in the description!)

### Bug description

I can't open Invoker-2.9.0.

Electron error thrown.

```
$ ./Invoker-2.9.0.AppImage 
loading plugins :: /home/bcryp7/.config/Invoker/plugins
(node:12632) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Unable to install `vue-devtools`: 
 Error: Exited with code 9
    at ChildProcess.<anonymous> (/tmp/.mount_InvokeEbOHqh/resources/app.asar/dist/electron/main.js:1:83533)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[12632:0903/003344.497013:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

I appreciate any guidance on this issue.

**Comment by elijahworkz** [comment]
Same exact issue here... 

I'm on Ubuntu 22.04 as well

PHP - 8.1.9

Invoker - 2.9.0

**Comment by mpociot** [comment]
To bypass this, please start Invoker from the CLI with the `--no-sandbox` flag.
This will be fixed in the next version of Invoker.

**Comment by albertorsesc** [comment]
@mpociot Thank you.
